#!/bin/bash

if [ $# -ne 1 ]
then
	echo "Usage: segment <settings file>"
	exit
fi

if [ -z "$AUTOMORPH_DIR" ]; then
    segment_dir="/hull-disk1/ph269/software/segment/current"
else
    segment_dir="${AUTOMORPH_DIR}/segment/src"
fi 

SETTINGSFILE=`readlink -f $1`

matlab -nodisplay -nodesktop -nosplash -r "addpath(${segment_dir}); segment('$SETTINGSFILE'); exit"
