#!/usr/bin/env python

import subprocess
import numpy as np
import sys
import shutil
import glob
import os
import cv2

settings = {
            'distance_to_first_plane': 915.0,
            'distance_between_planes': 0.9,
            'file_prefix': 'IMG',
            'file_extension': 'jpg'
            }


def scale(input_directory):

    print 'Scaling '+input_directory
    print settings

    planes = list_files(input_directory, settings)
    os.chdir(input_directory)

    if 'final' in os.path.split(planes[0])[1]:
        print 'Aborting: this directory has already been scaled.'
        return

    print "Resizing..."
    for i_plane, plane in enumerate(planes):

        print plane
        _, plane = os.path.split(plane)

        if i_plane == 0:
            command = ['identify', '-ping', plane]
            original_size_str = subprocess.check_output(command).split()[2]
            original_size = original_size_str.split('x')
            original_size = np.array([float(original_size[0]), float(original_size[1])])

            shutil.copy(plane, 'final_'+plane)

            image1 = cv2.imread(plane)

        else:
            ratio = settings['distance_to_first_plane'] / ((settings['distance_between_planes'] * i_plane) +
                                                           settings['distance_to_first_plane'])
            resize_str = str(ratio*100)+'%'

            command = ['convert', plane, '-resize', resize_str, 'scaled_'+plane]

            subprocess.call(command)

    print 'Recentering and adding padding...'

    for plane in planes[1:]:
        print plane
        _, plane = os.path.split(plane)

        image2 = cv2.imread('scaled_'+plane)

        result = cv2.matchTemplate(image1, image2, cv2.TM_CCOEFF_NORMED)
        offset = np.unravel_index(result.argmax(), result.shape)
        offset_str = '+'+str(offset[1])+'+'+str(offset[0])

        command = ['convert', '-size', original_size_str, 'xc: black',
                   '-page', offset_str, 'scaled_'+plane,
                   '-layers', 'flatten', 'final_'+plane]

        subprocess.call(command)

    clean_up(planes)


def clean_up(planes):
    '''
    This function deletes intermediate files created by scale
    and stashes the unscaled originals in an 'unscaled' directory
    '''
    print 'Cleaning up...'

    if not os.path.exists('unscaled'):
        os.makedirs('unscaled')

    for plane in planes:
        _, plane = os.path.split(plane)
        shutil.move(plane, 'unscaled')
        if os.path.exists('scaled_'+plane):
            os.remove('scaled_'+plane)


def list_files(directory, settings):
    '''
    This function takes a directory and returns a list of all images in that
    directory
    '''
    file_list = glob.glob(directory + os.sep + settings['file_prefix']
              + '*.' + settings['file_extension'])

    print 'INFO: images.find() found %d files' % len(file_list)

    return sorted(file_list)


if __name__ == "__main__":

    if len(sys.argv) == 2:
        scale(sys.argv[1])

    else:
        print 'Usage: scale <input_directory>'
        sys.exit('Error: incorrect usage')
